### ISSUE TITLE
Fit method for CellDiff2Vec is taking extremely long

### ISSUE THREAD

**Issue by devendragovil** [pyt-team/TopoEmbedX#25]
# What

When I am trying to use the fit method of CellDiff2Vec class on a relatively simple Cell Complex, it takes a really long time. It doesn't terminate in even 25 mins. I am not sure what I am doing wrong here. I just wanted to raise this issue, in case any one else is facing the same.

**Comment by ninamiolane** [comment]
@papamarkou please assign jarpri when he accepts the github invitation.

**Comment by papamarkou** [comment]
@ninamiolane sure, @jarpri will give it a go; @mhajij  kindly offered to point Jaro to a couple of relevant web links that will help inspect the matter.

**Comment by mhajij** [comment]
The easiest way to resolve this problem  is to look at the test example that this library is doing :

https://github.com/benedekrozemberczki/karateclub/blob/d750b33e8faaeb95ac2ed6d6ed4f0b470bd506ce/test/neighbourhod_based_node_embedding_test.py#L266

and then generate the correct cell complex accordingly. Our library calls this method since it runs on the example on the test case above then we might have been choosing wrong example to run our algorithm, Maybe it is also worth looking what kind of graphs Diff2Vec accepts as input, there might be some sort of restrictions (connected, or 2 connected or something like that).

**Comment by ninamiolane** [comment]
@papamarkou @jarpri what is the update on this?
